/**
 * generated by Xtext 2.15.0
 */
package pt.iscte.paddle.validation;

import pt.iscte.paddle.validation.AbstractJavaliValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class JavaliValidator extends AbstractJavaliValidator {
}
