/**
 * generated by Xtext 2.15.0
 */
package pt.iscte.paddle.ui.contentassist;

import pt.iscte.paddle.ui.contentassist.AbstractJavaliProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class JavaliProposalProvider extends AbstractJavaliProposalProvider {
}
