/*
 * generated by Xtext 2.17.0
 */
package pt.iscte.paddle.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractJavaliScopeProvider extends DelegatingScopeProvider {
}
