/**
 * generated by Xtext 2.15.0
 */
package pt.iscte.paddle;

import pt.iscte.paddle.AbstractJavaliRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class JavaliRuntimeModule extends AbstractJavaliRuntimeModule {
}
