/**
 * generated by Xtext 2.15.0
 */
package pt.iscte.paddle;

import pt.iscte.paddle.JavaliStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class JavaliStandaloneSetup extends JavaliStandaloneSetupGenerated {
  public static void doSetup() {
    new JavaliStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
