/**
 * generated by Xtext 2.15.0
 */
package pt.iscte.paddle.ide;

import pt.iscte.paddle.ide.AbstractJavaliIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class JavaliIdeModule extends AbstractJavaliIdeModule {
}
