/**
 * generated by Xtext 2.15.0
 */
package pt.iscte.paddle.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import pt.iscte.paddle.JavaliRuntimeModule;
import pt.iscte.paddle.JavaliStandaloneSetup;
import pt.iscte.paddle.ide.JavaliIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class JavaliIdeSetup extends JavaliStandaloneSetup {
  @Override
  public Injector createInjector() {
    JavaliRuntimeModule _javaliRuntimeModule = new JavaliRuntimeModule();
    JavaliIdeModule _javaliIdeModule = new JavaliIdeModule();
    return Guice.createInjector(Modules2.mixin(_javaliRuntimeModule, _javaliIdeModule));
  }
}
