/**
 * generated by Xtext 2.15.0
 */
package pt.iscte.paddle.scoping;

import pt.iscte.paddle.scoping.AbstractJavaliScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class JavaliScopeProvider extends AbstractJavaliScopeProvider {
}
